### ISSUE TITLE
error message image collection in Albedo

### ISSUE THREAD

**Issue by Ioannis-Faraslis** [rfernand387/LEAF-Toolbox#1]
Dear sir, 
Why when I tried to estimate Albedo, Fapar, etc I get the following error?
"Collection.loadTable: Collection asset 'users/rfernand387/COPERNICUS_S2_SR/COPERNICUS_S2_SR_DOMAIN' not found."
Please see the attached image
With best regards
![albedo](https://user-images.githubusercontent.com/62997735/110330524-82698c80-8026-11eb-821f-6a910148a55e.jpg)

**Comment by rfernand387** [comment]
Hi.  I know this is a long time laters but the code is now working fine.  It was an issue with firwewall permissions.  We are now actively supporting this code in collaboration with google.  Richard Fernandes
