### ISSUE TITLE
EE JavaScript function to utilize biophysical products 

### ISSUE THREAD

**Issue by eoags** [rfernand387/LEAF-Toolbox#3]
Dear Richard, I have been using time-series Landsat and Sentinel-2 data for vegetation trend analysis (LandTrendr) and land-use/land-cover classification to assist oil and gas reclamation assessment in Alberta. Biophysical products (e.g., LAI, FAPAR, FCOVER) from the LEAF toolbox would be really useful for reclamation assessment. I am requesting a function in Earth Engine JavaScript API to utilize these biophysical products for various temporal range in Alberta.
Regards,
Subir

**Comment by rfernand387** [comment]
[Function provided at ](https://github.com/rfernand387/LEAF-Toolbox/tree/master/Source-js)

closed
