### ISSUE TITLE
Cannot read property 'make_collection_options' of undefined

### ISSUE THREAD

**Issue by linqinan123** [rfernand387/LEAF-Toolbox#7]
Dear Richard Fernandez,

   It is an excellent app. When I run the  exmaple-SL2P, it appears the following error: In users/richardfernandes/SL2P:SL2P
Line 59: Cannot read property 'make_collection_options' of undefined.
https://code.earthengine.google.com/612b90449df9a8886cb80cd1fdcfc2b9

If would be great if you can fix these issues for us to use your excellent app. 
Lin

**Comment by rfernand387** [comment]
The source code was not up to date.  Now directly using the GEE git repo for source control.

Verified it works.  Richard
